Repository buddhabeard/trinity-site, pull requests merged in 2023-10, with the labels that each got.

#1 adds workflow steps and cleans up readme
  README.md
Labels: documentation

#2 adds store locations component to thrift store
  public/images/bg-desktop@2x.png:Zone.Identifier
  public/images/map-crawfordsville.jpg
  public/images/map-lafayette.jpg
  src/components/StoreLocations.astro
  src/pages/thrift-store.astro
Labels: enhancement

#8 adds blog listing items
  src/components/BlogPostsGrid.astro
  src/components/Carousel.tsx
  src/components/VideoWithContent.astro
  src/interfaces/Components.ts
  src/interfaces/Pages.ts
  src/lib/queries.ts
  src/pages/blog/index.astro
  src/pages/thrift-store.astro
  src/pages/who-we-are.astro
Labels: enhancement

#12 updating form links
  src/components/KindfulForm.astro
  src/pages/donate.astro
Labels: bug, enhancement

#37 trying fresh push
  src/components/Hero.tsx
  src/styles/site.css
Labels: styles
